# Generated by Django 5.2.7 on 2025-10-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('CANDIDATE', 'Кандидат'), ('HR-MANAGER', 'HR-менеджер')], default='CANDIDATE', max_length=150, unique=True),
        ),
    ]
